// SPDX-License-Identifier: AGPL-3.0-or-later
plugins {
    alias(libs.plugins.kotlin.android)
}

apply plugin: 'com.android.application'
android {
    namespace 'org.openresearchtools.wildbuzzard.probe'
    compileSdk { version = release(project.ext.compileSdkMajorVersion) { minorApiLevel = project.ext.compileSdkMinorVersion } }
    defaultConfig { applicationId 'org.openresearchtools.wildbuzzard.probe'; minSdk 28; targetSdk project.ext.targetSdkVersion; versionCode 1; versionName '0.1.0'; testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner' }
    buildFeatures { aidl true }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    sourceSets.main.aidl.srcDirs += '../wildbuzzard-sdk/src/main/aidl'
}

dependencies {
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.test.junit
    androidTestImplementation libs.androidx.test.uiautomator
}
