// SPDX-License-Identifier: AGPL-3.0-or-later
apply plugin: 'com.android.library'

android {
    namespace 'org.openresearchtools.wildbuzzard'
    compileSdk {
        version = release(project.ext.compileSdkMajorVersion) { minorApiLevel = project.ext.compileSdkMinorVersion }
    }
    defaultConfig {
        minSdk 28
        targetSdk project.ext.targetSdkVersion
        ndk { abiFilters 'arm64-v8a' }
        manifestPlaceholders = project.ext.manifestPlaceholders
    }
    buildFeatures { aidl true; buildConfig true }
    sourceSets.main.aidl.srcDirs += '../wildbuzzard-sdk/src/main/aidl'
    sourceSets.main.assets.srcDirs += "$buildDir/generated/notices"
    androidResources { noCompress 'ja' }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    sourceSets.main.jniLibs.srcDirs += "$buildDir/generated/tor"
    buildTypes {
        debug { debuggable true }
        release { minifyEnabled false }
    }
}

repositories {
    maven { url 'https://raw.githubusercontent.com/guardianproject/gpmaven/master' }
}

dependencies {
    implementation project(':geckoview')
    implementation libs.androidx.appcompat
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
    implementation 'info.guardianproject:jtorctl:0.4.5.7'
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
}

tasks.register('stageNotices', Exec) {
    commandLine 'python3', "${rootProject.projectDir}/wildbuzzard/android/scripts/notices.py", "$buildDir/generated/notices"
    inputs.files(fileTree("${rootProject.projectDir}/wildbuzzard/android/notices"))
    outputs.dir "$buildDir/generated/notices"
}
tasks.named('preBuild').configure { dependsOn 'stageNotices' }

tasks.register('stageTor', Exec) {
    commandLine 'python3', "${rootProject.projectDir}/wildbuzzard/android/scripts/tor.py", "$buildDir/generated/tor"
    inputs.file("${rootProject.projectDir}/wildbuzzard/android/scripts/tor.py")
    outputs.file("$buildDir/generated/tor/arm64-v8a/libtor.so")
}
tasks.named('preBuild').configure { dependsOn 'stageTor' }
